### ISSUE TITLE
[Express + Dropbox] req.efp.finished never executed

### ISSUE THREAD

**Issue by Fede91** [dannycho7/express-form-post#2]
Hi, I'm using your library to upload a file from express backend to Dropbox but the request remains pending. In the file dropbox.js, when the DropboxUploadStream is instantiated, the 'finish' event isn't catched as indicated in the library "Dropbox Stream" (https://github.com/velocityzen/dropbox-stream), but it's catched the 'done' event (never executed). 
I've tryed to change 'done' event with 'finish' and now the function req.efp.finished() is called.
Could you check and, if necessary, update the library?

This is the snippet that i'm using:

`var express = require("express");
var app = express();
var efp = require("express-form-post");

const formPost = efp({
    store: "dropbox",
    filename: function(req, file, cb) {
        cb(Date.now() + file.originalname);
    },
    api: {
        accessToken: access_token
    },
	promise: true
});

app.post("/upload", function(req, res, next) { 
	formPost.upload(req, res).then(() => {
		// add your response statements here
		console.log("The uploaded file information is located here:", req.files);
		res.status(200).send();
	}).catch((err) => {
		// add your catch statements here
		console.log(err);
	})
});
app.listen(3000, () => console.log('Server app listening on port 3000!'));`

**Comment by dannycho7** [comment]
Hey! Thanks for letting me know. You are correct. The module is not working as described in the documentation. Sorry for not noticing this. What happened was the dropbox-stream library got updated to v2.

I just changed the docs to correctly explain how to install the dropbox-stream library. What you will want to do is install v1.1 of the dropbox-stream library:

```sh
npm install dropbox-stream@1.1 --save
```

You can also find the change in documentation here: https://www.npmjs.com/package/express-form-post

Let me know if this works!

**Comment by Fede91** [comment]
Hi! I just tested the upload with the library  dropbox-stream@1.1 and now it works correctly.
Since you have updated the README, I close this issue.
Thank you!
